### ISSUE TITLE
Inline Bots freezes App on iOS 6.1.6

### ISSUE THREAD

**Issue by owiekindisch** [peter-iakovlev/Telegram#113]
I'm tried to use the @sticker and @gif Bot on my iPhone with iOS 6.1.6. The search results are appearing when I'm entering an emoji or a search term. That works very well, but if I tap on one result to send it the app freezes and crashes after a while. I guess this issue will appear on every inline bot.

**Comment by Cobowski** [comment]
Same issue on my iPod Touch 4th Gen with iOS 6.1.6.
