### ISSUE TITLE
Persian Text Rendering Problem within iOS 11's new font

### ISSUE THREAD

**Issue by pouyakary** [peter-iakovlev/Telegram#134]
Hi! hoping that you're great.

As of iOS 11, a new font has been introduced for Persian. The font is okay across all apps except Telegram. If you look:

<img src="https://user-images.githubusercontent.com/2157285/27005123-0cf3934e-4e2d-11e7-9f14-3127894d6ee0.jpg" width="200" />

If you look closely [dots](https://en.wikipedia.org/wiki/Dot_(diacritic)) are not rendered correctly. Some of them are higher than they should be.

Given the fact that no other app that I have has the same problem, it means you're using some special rendering system and this font is not good with that special system.

These are the characters that I found are troubling the render. And these are the test cases I think you should investigate:

```
ققق
ففف
غغغ
خخخ
تت
ثث
نن
```

**Comment by amirfrsd** [comment]
Hey, I have the same issue on iOS 11's New Font
