### ISSUE TITLE
(iOS 6) App Crashes due to Instant View

### ISSUE THREAD

**Issue by reinhart1010** [peter-iakovlev/Telegram#139]
Device: iPod Touch, 4th Generation
OS: iOS 6.1.6 (Last supported version for device)
Steps to reproduce:
1. Open a chatroom with Instant View links inside

or

2. Send an Instant View link from the device

Expected result: App works normal, with Instant View available.
Actual result: App hangs and eventually crashes.
Recommendation:
Enable option to disable Instant View (either by adding a toggle switch on Settings or disable it permanently for iOS 6)

**Comment by zpytchpp** [comment]
I'm also using ios 6.1.3 for iPhone 4s, and although telegram lets' you install from AppStore without warning, after hitting 'Start Messaging' button, the app crashes. It would be so nice to have at least this single messaging app working with ios 6..

**Comment by reinhart1010** [comment]
The Instant View problem was fixed in later releases, but I haven't checked again whether the bug will occur or not.
