### ISSUE TITLE
Ios 6.1.6 crash

### ISSUE THREAD

**Issue by Nikolaienko-Valerii** [peter-iakovlev/Telegram#188]
Telegram crashes anytime you try to open any chat.
Device: iPod Touch 4
OS: iOS 6.1.6
Telegram v4.5

**Comment by d-Rickyy-b** [comment]
This should be fixed in the latest v4.6 update. At least for me it is :) 👍

**Comment by Nikolaienko-Valerii** [comment]
Fixed in version 4.6
