### ISSUE TITLE
Button to set image from Photo Library as background wallpaper is missing. 

### ISSUE THREAD

**Issue by Ruukasu** [peter-iakovlev/Telegram#205]
When choosing an image from the Photo Library via Telegram v4.7 for iOS, there is no bottom set of buttons "Set" and "Cancel", therefore I can no longer set any image stored in my device as background wallpaper. I believe that this is a broken feature.

**Comment by sattagon54** [comment]
Same issue. Theres no buttons for iPad (v4.7)

**Comment by Ruukasu** [comment]
4.7.1 resolved this issue. Thank you.
