### ISSUE TITLE
[Fixed] 'MTProtoKitDynamic/MTContext.h' file not found inside TGDatacenterConnectionContext.h

### ISSUE THREAD

**Issue by takasurazeem** [peter-iakovlev/Telegram#266]
just cloned the repo and built the project

Been missing submodules.

**Comment by chris118** [comment]
how to fix? I still have this issue

**Comment by takasurazeem** [comment]
@chris118 you are missing the submodules.

**Comment by frakman1** [comment]
I cloned the project and opened the .xcworkspace. What target do I select for the iOS iPhone app?
These are all the options:

![image](https://user-images.githubusercontent.com/5826484/51768107-58a2b500-20ad-11e9-8bd5-10c56bb23050.png)

I chose Telegram-iOS-Fork which was the first one that started to compile but I get this error:
`Telegram-iOS/Share/TGItemProviderSignals.h:1:9: error: 'MTProtoKitDynamic/MTProtoKitDynamic.h' file not found`

Sorry for the beginner question, but how do I get `missing submodules` ?
