### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by qadir-genetech** [peter-iakovlev/Telegram#36]
Swift support will be great :+1:

**Comment by AlexKMDev** [comment]
What kind of support do you need?

**Comment by qadir-genetech** [comment]
I mean to say Re write the whole app in Swift :)

**Comment by ratijas** [comment]
@qadirsuh go away. iOS 6 one love forever.

**Comment by qadir-genetech** [comment]
:D thought so : p

**Comment by qadir-genetech** [comment]
can you tell me where can I get a bug free copy of the telegram App please?
