### ISSUE TITLE
Bring back old TGAudioRecorder UI & SFSafariViewController

### ISSUE THREAD

**Issue by joemerlino** [peter-iakovlev/Telegram#38]
The new one has a less accurate tracking on iPads, it dismisses recordings randomly. 

Bring back SFSafariViewController on iPads.

**Comment by skomik** [comment]
The reason why SFSafariViewController is disabled on iPad now seems like a bug to me. The following condition will never be true.

https://github.com/peter-iakovlev/Telegram/blob/2f6729c9d4cb55dd5b6701edd5fc3f5d732206c8/Telegraph/TGApplication.m#L251

**Comment by joemerlino** [comment]
I did make an iOS jailbreak tweak to bring back some of the stuff taken away from iPads.

Just submitted to BigBoss, should be available in a couple of days.
