### ISSUE TITLE
app crash when uploading video to supergroup

### ISSUE THREAD

**Issue by sadalhayat** [peter-iakovlev/Telegram#60]
Telegram iOS crash when uploading video to supergroup.
no problem on private or common group.

Thanks,
@sadal

**Comment by sadalhayat** [comment]
Telegram v3.10

**Comment by ghost** [comment]
i don't see a value in posing issue here
cuz first of all they should update source code

**Comment by sadalhayat** [comment]
yea too bad 😰

btw bug fixed in new version 3.10.1 👍
