### ISSUE TITLE
питер пожалуйста, прочитайте это!

### ISSUE THREAD

**Issue by ghost** [peter-iakovlev/Telegram#62]
Привет Питер
я сделал клиент телеграммы с помощью этого исходного кода 2,3 месяца назад
но почему вы остановили его обновления?
последнее обновление 4 месяца назад?
пожалуйста, обновите этот исходный код, который мы действительно это нужно!
я знаю, что вы читаете это :)
пожалуйста, просто сделать это, спасибо

**Comment by EvgenyKarkan** [comment]
Google translate rules :)

**Comment by ghost** [comment]
@EvgenyKarkan i thought it may works! but it didn't
