### ISSUE TITLE
<SSignalKit/SSignalKit.h> file not found

### ISSUE THREAD

**Issue by soant** [peter-iakovlev/Telegram#7]
After add the mdb.c file，there is another error “<SSignalKit/SSignalKit.h> file not found” when the project compiled.

**Comment by EdoEscada** [comment]
Same problem with me, but I can find that file by searching. Located in other location like the folder "thirdparty". That folder must be match with the direction within project. Sorry very new for xCode. First day :( ... anyone can help ?

**Comment by chriscoderdr** [comment]
just run git submodule update --init --recursive to download all the dependencies.

**Comment by qadir-genetech** [comment]
I ran command git submodule update --init --recursive

but got this
`Qadirs-Mac-mini:Telegram qadirhussain$ git submodule update --init --recursive
Cloning into 'submodules/elements'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@bitbucket.org:iakovlevpeterp/elements.git' into submodule path 'submodules/elements' failed`

**Comment by 9JX** [comment]
I have the same problem with you. Did you resolved it？ @qadirsuh

**Comment by qadir-genetech** [comment]
Nope. :(

**Comment by hakim-ali** [comment]
I have same problem.

**Comment by sadegh2007** [comment]
same problem

**Comment by Adizbek** [comment]
@qadirsuh, @songjianboy . I found the solution. Just open `.gitmodules` file. Change `url = git@github.com:iakovlev-peter/MtProtoKit.git` to `url=https://github.com/peter-iakovlev/MtProtoKit.git`. If still you're getting error try to change file `.git/config`, you can find there url like above just change it too.
