### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by whateverx** [peter-iakovlev/Telegram#83]
@peter-iakovlev will you update the code ? latest updates are awesome ☺️👍🏻

**Comment by hasanzadeh-arianrp** [comment]
Please publish latest features.

**Comment by ghost** [comment]
😐

**Comment by mosqueiro** [comment]
This project will certainly not be updated any more

**Comment by hasanzadeh-arianrp** [comment]
why?

**Comment by mosqueiro** [comment]
@hasanzadeh-arianrp this code will not be updated, I asked the Telegram several times and I did not succeed. They will no longer update the source code for IOS, give up

**Comment by whateverx** [comment]
Ok thank you 👍
